name: propertyestimator
channels:
    - conda-forge
    - omnia
dependencies:
    # Base depends
    - python ==3.6
    - setuptools

    # Sphinx specific
    - numpydoc
    - nbsphinx
    - m2r >=0.2.1
    - sphinx_rtd_theme

    # Standard dependencies
    - numpy
    - pandas
    - lxml
    - icu 58*  # REQUIRED - DO NOT REMOVE.
    - openmm
    - pint
    - packmol
    - pymbar
    - dask >=2.2
    - distributed >=2.2
    - dask-jobqueue >=0.6.2
    - tornado <6
    - uncertainties
